spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 600000
      pool-name: PostgresHikariPool
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:/db/migration
    validate-on-migrate: true
    encoding: UTF-8

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  info:
    title: CRUD API Documentation
    description: Description of my CRUD
    version: 1.0
    contact:
      name: Alex
      email: alex@gmail.com
  security:
    enabled: false